services:
    reverseproxy:
        image: techjam-reverseproxy-image
        build: ./reverseproxy
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./reverseproxy/conf.d:/etc/nginx/conf.d
            - ./reverseproxy/ssl:/etc/nginx/ssl
            - ./reverseproxy/html:/usr/share/nginx/html
            - ./reverseproxy/logs:/var/log/nginx
        depends_on:
            - server
    server:
        image: techjam-server-image
        build: ./server
        ports:
            - "8080:8080"
        env_file:
            - server.env
        depends_on:
            database:
                condition: service_healthy
    database:
        image: techjam-database-image
        build: ./database
        ports:
            - "27017:27017"
        volumes:
            - ./database/data:/data/db
        env_file:
            - database.env
        healthcheck:
            test: ["CMD-SHELL", "mongo --eval 'db.adminCommand('ping')'"]
            interval: 30s
            timeout: 10s
            retries: 5
